---
- name: play for ecomm web application deployment
  hosts: all   
  become: yes   

  tasks: 
    - name: update package index
      apt: 
        update_cache: yes

    - name: install nginx
      apt: 
        name: nginx 
        state: latest

    - name: start and enable nginx
      service: 
        name: nginx
        state: started
        enabled: yes
    
    - name: ensure git is installed
      apt:
        name: git
        state: present

    - name: clean the web directory
      file:
        path: /var/www/html
        state: absent

    - name: create the web directory
      file:
        path: /var/www/html
        state: directory

    - name: git clone
      git:
        repo: https://github.com/ash2code/ansible-jenkins-ecomm-app.git
        dest: /var/www/html
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
